const SLACK_API = "https://slack.com/api/chat.postMessage";

function riskColor(flag) {
  if (flag.includes("🟢")) return "#E24B4A";
  if (flag.includes("🟡")) return "#EF9F27";
  return "#1D9E75";
}

export async function postFeedbackToSlack(ae, meetingData, scoring) {
  const channel = process.env.SLACK_CHANNEL || "#callhippo-qa-feedback";
  const token = process.env.SLACK_BOT_TOKEN;
  if (!token) throw new Error("SLACK_BOT_TOKEN not set");

  const c = scoring.criteriaScores || {};

  // Dynamic criteria — works for any call type
  const criteriaLine = Object.entries(c)
    .map(([key, val]) => {
      const label = key
        .replace(/([A-Z])/g, " $1")
        .replace(/^./, s => s.toUpperCase())
        .trim();
      return `${label}: ${val}/10`;
    })
    .join(" | ");

  const callTypeLabel = (scoring.callType || "call").charAt(0).toUpperCase() + (scoring.callType || "call").slice(1);

  const blocks = [
    { type: "header", text: { type: "plain_text", text: `📞 Call Feedback — ${ae.name}`, emoji: true }},
    { type: "section", fields: [
      { type: "mrkdwn", text: `*Meeting:*\n${meetingData.title}` },
      { type: "mrkdwn", text: `*Type:*\n${callTypeLabel}` },
      { type: "mrkdwn", text: `*Duration:*\n${meetingData.duration}` },
      { type: "mrkdwn", text: `*Team:*\n${ae.team}` },
    ]},
    { type: "divider" },
    { type: "section", text: { type: "mrkdwn", text: `*Score: ${scoring.callScore}/10* ${scoring.riskFlag}` }},
    { type: "section", text: { type: "mrkdwn", text: `*Criteria:*\n${criteriaLine}` }},
    { type: "divider" },
    { type: "section", text: { type: "mrkdwn", text: `✅ *What Was Good*\n${(scoring.whatWasGood || []).map(s => `• ${s}`).join("\n")}` }},
    { type: "section", text: { type: "mrkdwn", text: `⚠️ *What Can Be Better*\n${(scoring.whatCanBeBetter || []).map(i => `• ${i}`).join("\n")}` }},
    { type: "section", text: { type: "mrkdwn", text: `💡 *Hot Take:* ${scoring.hotTake}` }},
    { type: "divider" },
    { type: "section", fields: [
      { type: "mrkdwn", text: `*Next Call Focus:*\n${scoring.nextCallFocus || "—"}` },
      { type: "mrkdwn", text: `*Next 24 hrs:*\n${scoring.remarkNextSteps || "—"}` },
    ]},
    { type: "context", elements: [{ type: "mrkdwn", text: `<${meetingData.grainUrl}|View Grain recording> · Auto-generated by CallHippo QA Agent` }]},
  ];

  const res = await fetch(SLACK_API, {
    method: "POST",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      channel,
      text: `Call Feedback for ${ae.name}: ${scoring.callScore}/10 ${scoring.riskFlag}`,
      attachments: [{ color: riskColor(scoring.riskFlag), blocks }],
    }),
  });

  const result = await res.json();
  if (!result.ok) throw new Error(`Slack error: ${result.error}`);
  console.log(`[Slack] Posted for ${ae.name} — ts: ${result.ts}`);
}
